backend:
  name: github
  repo: wesleyweazin/netlify-cms-blog

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Chinese Title", name: "title_zh", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Cover Image",name: "cover",widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Chinese Title", name: "title_zh", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Cover Image",name: "cover",widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "shots"
    label: "Shots"
    folder: "content/shots"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Chinese Title", name: "title_zh", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Cover Image",name: "cover",widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
